name: PHP Composer

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      max-parallel: 4
      matrix:
        php-version: ['7.0', '7.1', '7.2', '7.3']

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: php${{ matrix.php-version }} /usr/bin/composer validate

    - name: Install dependencies
      run: php${{ matrix.php-version }} /usr/bin/composer install --prefer-dist --no-progress --no-suggest

    - name: Run test suite
      run: php${{ matrix.php-version }} /usr/bin/composer run-script test
